// Re-export all table definitions from individual files
export * from './core'
export * from './payments'
export * from './messaging'
export * from './gamification'
export * from './trading'
export * from './freelance-core'
export * from './jobs'
export * from './workspace'
export * from './reputation'
export * from './marketing'
export * from './support'
export * from './system'
export * from './relations'
export * from './types'
