// Activity types that can be used on both client and server
// This is a duplicate of the ActivityType enum from schema.ts for client-side use

export enum ActivityType {
  // Security activities
  SIGN_IN = 'SIGN_IN',
  SIGN_OUT = 'SIGN_OUT',
  SIGN_UP = 'SIGN_UP',
  WALLET_CONNECTED = 'WALLET_CONNECTED',
  WALLET_DISCONNECTED = 'WALLET_DISCONNECTED',
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  USER_UPDATED_BY_ADMIN = 'USER_UPDATED_BY_ADMIN',
  USER_DELETED_BY_ADMIN = 'USER_DELETED_BY_ADMIN',
  BULK_USER_ROLES_UPDATED = 'BULK_USER_ROLES_UPDATED',
  UPDATE_PASSWORD = 'UPDATE_PASSWORD',
  DELETE_ACCOUNT = 'DELETE_ACCOUNT',
  UPDATE_ACCOUNT = 'UPDATE_ACCOUNT',
  UPDATE_PROFILE = 'UPDATE_PROFILE',

  // Team activities
  CREATE_TEAM = 'CREATE_TEAM',
  INVITE_TEAM_MEMBER = 'INVITE_TEAM_MEMBER',
  ACCEPT_INVITATION = 'ACCEPT_INVITATION',
  REJECT_INVITATION = 'REJECT_INVITATION',
  REMOVE_TEAM_MEMBER = 'REMOVE_TEAM_MEMBER',
  UPDATE_TEAM_MEMBER_ROLE = 'UPDATE_TEAM_MEMBER_ROLE',
  TEAM_CREATED = 'TEAM_CREATED',
  TEAM_UPDATED = 'TEAM_UPDATED',
  TEAM_DELETED = 'TEAM_DELETED',
  MEMBER_ADDED = 'MEMBER_ADDED',
  MEMBER_REMOVED = 'MEMBER_REMOVED',

  // Billing activities
  PAYMENT_INITIATED = 'PAYMENT_INITIATED',
  PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_COMPLETED = 'PAYMENT_COMPLETED',
  SUBSCRIPTION_ACTIVATED = 'SUBSCRIPTION_ACTIVATED',
  SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED',
  SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED',
  SUBSCRIPTION_CREATED = 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_UPDATED = 'SUBSCRIPTION_UPDATED',
  SUBSCRIPTION_CANCELED = 'SUBSCRIPTION_CANCELED',
  SUBSCRIPTION_UPGRADED = 'SUBSCRIPTION_UPGRADED',
  SUBSCRIPTION_UPDATED_BY_ADMIN = 'SUBSCRIPTION_UPDATED_BY_ADMIN',
  TEAM_PLAN_DOWNGRADED = 'TEAM_PLAN_DOWNGRADED',
  SUBSCRIPTION_DOWNGRADED = 'SUBSCRIPTION_DOWNGRADED',

  // Trade activities
  TRADE_CREATED = 'TRADE_CREATED',
  TRADE_FUNDED = 'TRADE_FUNDED',
  TRADE_DELIVERED = 'TRADE_DELIVERED',
  TRADE_ACCEPTED = 'TRADE_ACCEPTED',
  TRADE_RELEASED = 'TRADE_RELEASED',
  TRADE_DISPUTED = 'TRADE_DISPUTED',
  TRADE_CANCELLED = 'TRADE_CANCELLED',
  TRADE_REFUNDED = 'TRADE_REFUNDED',
  TRADE_EXPIRED = 'TRADE_EXPIRED',
  TRADE_COMPLETED = 'TRADE_COMPLETED',
  TRADE_DELIVERED_BY_SELLER = 'TRADE_DELIVERED_BY_SELLER',
  TRADE_MARKED_AS_COMPLETE = 'TRADE_MARKED_AS_COMPLETE',
  TRADE_CHAT_MESSAGE = 'TRADE_CHAT_MESSAGE',
  TRADE_STATUS_CHANGED = 'TRADE_STATUS_CHANGED',
  TRADE_UPDATED = 'TRADE_UPDATED',
  ESCROW_FUNDED = 'ESCROW_FUNDED',
  ESCROW_RELEASED = 'ESCROW_RELEASED',

  // Legal documents
  LEGAL_DOCUMENT_UPDATED = 'LEGAL_DOCUMENT_UPDATED',

  // API Keys
  API_KEY_CREATED = 'API_KEY_CREATED',
  API_KEY_DELETED = 'API_KEY_DELETED',
  API_KEY_REGENERATED = 'API_KEY_REGENERATED',

  // Blockchain activities
  BLOCKCHAIN_CONFIG_CREATED = 'BLOCKCHAIN_CONFIG_CREATED',
  BLOCKCHAIN_CONFIG_UPDATED = 'BLOCKCHAIN_CONFIG_UPDATED',
  BLOCKCHAIN_CONFIG_DELETED = 'BLOCKCHAIN_CONFIG_DELETED',

  // Battle activities
  BATTLE_INITIATED = 'BATTLE_INITIATED',
  BATTLE_ACCEPTED = 'BATTLE_ACCEPTED',
  BATTLE_REJECTED = 'BATTLE_REJECTED',
  BATTLE_STARTED = 'BATTLE_STARTED',
  BATTLE_ROUND_COMPLETED = 'BATTLE_ROUND_COMPLETED',
  BATTLE_COMPLETED = 'BATTLE_COMPLETED',
  BATTLE_EXPIRED = 'BATTLE_EXPIRED',
  BATTLE_CREATED = 'BATTLE_CREATED',
  BATTLE_TRADE_SUBMITTED = 'BATTLE_TRADE_SUBMITTED',
  BATTLE_WON = 'BATTLE_WON',
  BATTLE_LOST = 'BATTLE_LOST',
  BATTLE_DRAW = 'BATTLE_DRAW',

  // Admin activities
  ADMIN_ACTION = 'ADMIN_ACTION',
  BULK_UPDATE_LEGAL_DOCUMENTS = 'BULK_UPDATE_LEGAL_DOCUMENTS',
  ACTIVITY_LOG_EXPORTED = 'ACTIVITY_LOG_EXPORTED',
  ADMIN_DISPUTE_RESOLVED = 'ADMIN_DISPUTE_RESOLVED',
  DISPUTE_CREATED = 'DISPUTE_CREATED',
  DISPUTE_RESOLVED = 'DISPUTE_RESOLVED',
  DISPUTE_ESCALATED = 'DISPUTE_ESCALATED',
  DISPUTE_STATUS_CHANGED = 'DISPUTE_STATUS_CHANGED',

  // Listing activities
  LISTING_CREATED = 'LISTING_CREATED',
  LISTING_UPDATED = 'LISTING_UPDATED',
  LISTING_DELETED = 'LISTING_DELETED',
  LISTING_ACCEPTED = 'LISTING_ACCEPTED',

  // Message activities
  NEW_MESSAGE = 'NEW_MESSAGE',
  UNREAD_MESSAGES = 'UNREAD_MESSAGES',
  MESSAGE_DELETED = 'MESSAGE_DELETED',

  // Battle match activities
  BATTLE_MATCH_FOUND = 'BATTLE_MATCH_FOUND',

  // Team invitation activities
  TEAM_INVITATION = 'TEAM_INVITATION',
  TEAM_JOINED = 'TEAM_JOINED',
  TEAM_LEFT = 'TEAM_LEFT',
  TEAM_KICKED = 'TEAM_KICKED',
  UPDATE_TEAM_ROLE = 'UPDATE_TEAM_ROLE'
}
